# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 14:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='文章正文'),
        ),
    ]
