# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0003_articlescollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
