# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 01:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='任务标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='任务内容')),
                ('reward', models.PositiveIntegerField(default=0, verbose_name='酬劳')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'permissions': (('can_change_task', '可以修改任务信息'), ('can_add_task', '可以添加任务信息')),
            },
        ),
    ]
