# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='tasks/%Y%m%d/'),
        ),
    ]
